# -*- mode: ruby -*-
# vi: set ft=ruby :

servers=[
  {
    :hostname => "swarm0",
    :ip => "192.168.100.10"
  },{
    :hostname => "swarm1",
    :ip => "192.168.100.11"
  },{
    :hostname => "swarm2",
    :ip => "192.168.100.12"
  }
]

$script = <<SCRIPT
   echo "deb https://apt.dockerproject.org/repo ubuntu-xenial testing" > /etc/apt/sources.list.d/docker.list
   apt-key adv --keyserver hkp://ha.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
   apt-get update
   apt-get install -y --allow-unauthenticated docker-engine
   # Download 1.13.0-rc1-experimental
   if [ ! -f /vagrant/binary-daemon.tar ];then
     curl -fsLo /vagrant/binary-daemon.tar https://github.com/ChristianKniep/docker/releases/download/1.13.0-rc1-exp/binary-daemon.tar
   fi
   tar xf /vagrant/binary-daemon.tar -C /usr/bin/ >/dev/null
   if [ ! -f /vagrant/binary-client.tar ];then
     curl -fsLo /vagrant/binary-client.tar https://github.com/ChristianKniep/docker/releases/download/1.13.0-rc1-exp/binary-client.tar
   fi
   tar xf /vagrant/binary-client.tar -C /usr/bin/ >/dev/null
   cp /vagrant/daemon.json /etc/docker/
   cp /vagrant/docker.service /lib/systemd/system/docker.service
   systemctl daemon-reload
   service docker restart
   if [ "$(hostname)" == "swarm0" ];then
     docker swarm init --advertise-addr=192.168.100.10
     docker swarm join-token manager -q > /vagrant/token
     sleep 2
     # download image
     for img in alpn-consul alpn-grafana3 influxdb;do
       docker pull qnib/${img}
     done
     # create Metric network
     docker network create -d overlay metric-net
     # create service
     docker service create --replicas=1 --name consul --network=metric-net \
                           --port target=8500,published=8500,mode=ingress \
                           -e CONSUL_BOOTSTRAP_EXPECT=1 \
                           qnib/alpn-consul

     sleep 5
     docker service create --replicas=1 --name influxdb --network=metric-net \
                           --port target=8083,published=8083,mode=ingress \
                           --port target=8086,published=8086,mode=ingress \
                           -e INFLUXDB_DATABASES=qcollect -e CONSUL_CLUSTER_IPS=consul \
                           qnib/influxdb
     docker service create --replicas=1 --name grafana3 --network=metric-net \
                           -e CONSUL_CLUSTER_IPS=consul \
                           --port target=3000,published=3000,mode=ingress \
                           qnib/alpn-grafana3
     docker service create --name http --mode=global --mode=global \
                           --port target=80,published=80,mode=ingress qnib/httpcheck
   fi
   if [ "$(hostname)" == "swarm1" ];then
     docker swarm join --token $(cat /vagrant/token) --advertise-addr=192.168.100.11 192.168.100.10:2377
   fi
   if [ "$(hostname)" == "swarm2" ];then
     docker swarm join --token $(cat /vagrant/token) --advertise-addr=192.168.100.12 192.168.100.10:2377
   fi
   wget -qO /usr/local/bin/qcollect  https://github.com/qnib/qcollect/releases/download/0.7.0.1/qcollect_0.7.0.1-dirty-1_Linux
   chmod +x /usr/local/bin/qcollect
   cp -r /vagrant/qcollect* /etc/
   sed -i"" -e "s/HOSTNAME/$(hostname -f)/" /etc/qcollect.conf
   cp /vagrant/qcollect.service /lib/systemd/system/
   systemctl enable qcollect
   systemctl start qcollect
SCRIPT

# This defines the version of vagrant
Vagrant.configure(2) do |config|
  servers.each do |machine|
    config.vm.define machine[:hostname] do |node|
      node.vm.box = "bento/ubuntu-16.04"
      node.vm.hostname = machine[:hostname]
      node.vm.network "private_network", ip: machine[:ip]
      node.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--memory", 2048]
      end
      node.vm.provision "shell" do |s|
        s.inline = $script
      end
    end
  end
end
