$script = <<SCRIPT
   apt-get update
   rm -f /var/lib/apt/lists/lock
   apt-get install -y apt-transport-https ca-certificates unzip wget
   apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
   echo "deb https://mirror.azure.cn/docker-engine/apt/repo debian-jessie main" > /etc/apt/sources.list.d/docker.list
   apt-get update
   apt install -y docker-engine=1.10.0-0~jessie
   usermod -aG docker vagrant
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "debian/jessie64"
  config.vm.provision "shell" do |s|
        s.inline = $script
      end
end
