# -*- mode: ruby -*-
# vi: set ft=ruby :

servers=[
  {
    :hostname => "swarm0",
    :ip => "192.168.100.10"
  },{
    :hostname => "swarm1",
    :ip => "192.168.100.11"
  },{
    :hostname => "swarm2",
    :ip => "192.168.100.12"
  },{
    :hostname => "swarm3",
    :ip => "192.168.100.13"
  }
]

$script = <<SCRIPT
    set -x
    systemctl stop docker
    cd /root/
    cp /vagrant/daemon.json /etc/docker/
    cp /vagrant/docker.service /lib/systemd/system/docker.service
    systemctl daemon-reload
    rm -rf /var/lib/docker/*
    service docker start
    mkdir -p /home/user/.ssh/
    cp /vagrant/ssh/* /home/user/.ssh/
    chown -R user: /home/user
    useradd --no-create-home --shell /bin/bash user
    if [ "$(hostname)" == "swarm0" ];then
        docker swarm init --advertise-addr=192.168.100.10
        docker swarm join-token manager -q > /vagrant/token
        go build -o /usr/local/bin/go-dssh /usr/local/src/go-dssh.go
        fi
    if [ "$(hostname)" == "swarm1" ];then
        docker swarm join --token $(cat /vagrant/token) --advertise-addr=192.168.100.11 192.168.100.10:2377
        fi
    if [ "$(hostname)" == "swarm2" ];then
        docker swarm join --token $(cat /vagrant/token) --advertise-addr=192.168.100.12 192.168.100.10:2377
    fi
    if [ "$(hostname)" == "swarm3" ];then
        docker swarm join --token $(cat /vagrant/token) --advertise-addr=192.168.100.13 192.168.100.10:2377
    fi
    #### Munge
    cp /vagrant/slurm/munge.key /etc/munge/
    chown -R munge /etc/munge/munge.key
    chmod 400 /etc/munge/munge.key
    systemctl restart munge
    #### Slurm config
    cp /vagrant/slurm/slurm.conf /etc/slurm-llnl/
    cp /vagrant/slurm/slurmctld.service /lib/systemd/system/
    cp /vagrant/slurm/slurmd.service /lib/systemd/system/
    systemctl daemon-reload
    cp /vagrant/slurm/slurmctld.default /etc/default/slurmctld
    cp /vagrant/slurm/slurmd.default /etc/default/slurmd
    mkdir -p /var/spool/slurm.spool
    chown -R slurm: /var/spool/slurm.spool
    mkdir -p /var/spool/slurm.state
    chown -R slurm: /var/spool/slurm.state
    if [ "$(hostname)" == "swarm0" ];then
        systemctl restart slurmctld
    else
        systemctl disable slurmctld
        systemctl stop slurmctld
    fi
    systemctl restart slurmd
SCRIPT

## Environment
ENV["LC_ALL"] = "en_US.UTF-8"

# This defines the version of vagrant
Vagrant.configure(2) do |config|
  servers.each do |machine|
    config.ssh.username = "vagrant"
    config.ssh.password = "vagrant"
    config.vm.synced_folder "src/", "/usr/local/src/"
    config.vm.synced_folder "bin/", "/usr/local/bin/"
    config.vm.define machine[:hostname] do |node|
      node.vm.box = "qnib/u17-swarm"
      node.vm.hostname = machine[:hostname]
      node.vm.network "private_network", ip: machine[:ip]
      node.vm.provider "virtualbox" do |vb|
        vb.memory = 1024
        vb.cpus = 1
      end
      node.vm.provision "shell" do |s|
        s.inline = $script
      end
    end
  end
end
